name: Build and Push Docker Image

# Trigger the workflow on push to specific branches
on:
  push:
    branches:
      - main
      - staging
      - development
    paths:
      - 'src/**/*'  # Only run the workflow if changes happen in the 'src/' directory

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.madhawi1999 }}/demodocker:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.madhawi1999 }}
          password: ${{ secrets.Mad99&ki98 }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.madhawi1999 }}/demodocker:latest
