name: Docker Build and Push

# Trigger the workflow on push to specific branches
on:
  push:
    branches:
      - main
      - staging
      - development
    paths:
      - 'src/**/*'  # Only run the workflow if changes happen in the 'src/' directory

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    # Step 4: Build and push the Docker image
    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_REPOSITORY }}:latest .
        docker push ${{ secrets.DOCKER_HUB_REPOSITORY }}:latest
